### ISSUE TITLE
can't compile in Xcode 8.1

### ISSUE THREAD

**Issue by qgliu** [akosma/SwiftMoment#78]
I use carthage. The version 0.7 can't be built but 0.6 works.

Here is the failure output

MomentTests.swift:13:1: error: Type Body Length Violation: Type body should span 350 lines or less excluding comments and whitespace: currently spans 400 lines (type_body_length)

**Comment by markmadlangbayan** [comment]
I'm getting this same error too.

**Comment by madhavajay** [comment]
Looks like the 0.7 tag on github is actually from last year.
Try in your Cartfile:
```
github "akosma/SwiftMoment" "master"
```

Or pin it to the commit "fe37d80ad8cfda2de44356166b39b9e91633cf7b"

@akosma might be worth doing a clean up with a version bump and update to info.plist files, cocoapods and a new github tag for Carthage to 0.71 or 0.8 or something just to force and update and keep everything in sync.

The current master tests pass and it builds on Carthage (I use Carthage so I know it works since this is why I updated the project to Swift 4).

@qgliu @markmadlangbayan let me know if this resolves the issue for now.
You can also browse the commits and pin to an older version hash if you need something from an earlier swift version as well.

**Comment by markmadlangbayan** [comment]
@madhavajay thanks!  I'll switch to master once we're on Swift 4.  For now, I temporarily forked it and removed the swiftlint.

**Comment by madhavajay** [comment]
No problems! 👍
